// <auto-generated />
using System;
using DataForLab5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataForLab5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231108105711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DataForLab5.Entities.ContactEntity", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Birth = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adam@wsei.pl",
                            Name = "Adam",
                            Phone = "123123123"
                        },
                        new
                        {
                            ContactId = 2,
                            Birth = new DateTime(2002, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maciek@wsei.pl",
                            Name = "Maciek",
                            Phone = "345345345"
                        },
                        new
                        {
                            ContactId = 3,
                            Birth = new DateTime(2002, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bartosz@wsei.pl",
                            Name = "Bartosz",
                            Phone = "345234123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
